```{r}
#install.packages('arules')
#install.packages('arulesViz')
#install.packages('plyr', dependencies=TRUE)
library(arules)
library(arulesViz)
library(plyr)
```

```{r}
# Get data
pwd = '/Users/elikravitz/Desktop/CU_Classes/Current/CSCI5622/final_project/code'
data_file = file.path(pwd, 'arm_data', '2013.csv')
data = read.csv(data_file)

trans = as(data, 'transactions')
rules = apriori(trans, parameter=list(support=0.002, confidence=0.5, minlen=3, maxlen=5))
```

```{r}
plot(rules, method='grouped')
```

```{r}
# Get snowfall rules
snowfall_rules = subset(rules, subset=rhs %pin% 'snowfall=y')
```

```{r}
inspect(head(sort(snowfall_rules, by='support'), 15))
```

```{r}
inspect(head(sort(snowfall_rules, by='confidence'), 15))
```

```{r}
inspect(head(sort(snowfall_rules, by='lift'), 15))
```

```{r}
# Filter rules for plotting
snowfall_rules = subset(snowfall_rules, subset=lift > 5)
snowfall_rules = subset(snowfall_rules, subset=confidence > 0.7)
plot(snowfall_rules, method='grouped')
```